language: groovy

jdk:
    - oraclejdk7

before_install:
    - sudo add-apt-repository -y ppa:groovy-dev/grails
    - sudo apt-get update
    - sudo apt-get install grails-ppa
    - sudo apt-get install grails-2.4.0


script: grails refresh-dependencies
    && grails war docker/docker-registry-web.war
