language: groovy
after_success: 
- travis-artifacts upload --path docker-registry-web.war --target-path build/
script: ./grailsw war docker-registry-web.war
env: 
  global: 
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=github-docker-registry-web"
   - secure: "cGr2uDV4iQPxgO9Q3S0ZvDPh4Cd8Jtl5m2mxE1d1Oz81TItAGcKDioKP+5kR0ppSBCoYX/Xv1WdvKxG5zkiYCt4z3A71C65phDFWGm7W+tANLPXz3dmHWGYP72ulg2I2mgnxnorDWKY+9hVeIgLWyaGxu4UTIyALh1/nEex+TJc="
   - secure: "dtLuvNxxZE6COI+SGCYELr+KbPjwpNEeP7ExOzdwm6Nz9SGhfuAM6r8/07YMcco0uB8vEv8oW/MH8ktpWE437ORLawDpl2vUwrs45lVWnmHZml2G+0h/ocqEtONFJPI0GDmiwdzF+hAahaeXeSzjNcfR1tIUSrt/15MvjRvNu68="

before_install: 
- gem install travis-artifacts

jdk: 
- oraclejdk7
