language: groovy

env: 
  global: 
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=github-docker-registry-web
  - secure: COuIFgZZaoKk+lZRuu9qX31dNAIHO+ThgDpCDQHDUE/mcmxRG3+0yElGl9MCn+1ZordudYIqUe9HlSWw3yPbLzyzCjSxshh3vKcYGYBjdG0ZA7OYf2NUKOz/HibTl5FmSYfxdLwJX08gm3iutTTBnmr7NQBCBKEdquDjj4X+cZU=
  - secure: S4xBwZhmt8ks3yuoNei2yW6oEdGrb45/+NuUZNm62odKQnhoSiALyyoDAtewZmOEdqh/qbGqsHcTmDgbqNq2zNCwlzKbFnDFJJ9sMVEP/FFqKPUORzt2MEakAqiegaOoPkrMeDa18wwvzdLeA1Q3zTQrBKdrHzm9nLPNooyODKA=

jdk: 
    - oraclejdk7

before_install: 
    - gem install travis-artifacts

script: ./grailsw war docker-registry-web.war

after_success: 
    - travis-artifacts upload --path docker-registry-web.war --target-path build/
