language: groovy

jdk:
    - oraclejdk7

before_install:
    - curl -s get.gvmtool.net | bash
    - yes y | gvm install grails

script: grails refresh-dependencies
    && grails war docker/docker-registry-web.war
