language: groovy
after_success: 
- travis-artifacts upload --path docker-registry-web.war --target-path build/
script: ./grailsw war docker-registry-web.war
env: 
  global: 
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=github-docker-registry-web"
  - secure: ZVotiXw0/rP2cvuaTX0SvjAff2QOtsrkUNl6/kVx/wdVBopzprGNIKpyCEam4HJQ/Gh+zWJpoIFB1V0vNnyZHkqe9p/40S2vaXSfEKyL0yk6RYVQVqKjxC+P4OSkNY14ZvFJw1xF9nbzJUB4ncUiPcF+t522/6xb3f4ZD4jH98A=
  - secure: S/giuxzx6UxvkYR6iSw6nRYabME4weiJKGbWhGx3kCDkr5wLBWx8y7EvoaHNnTBoBh1IBPiZFo6CCc6yTGqwP2YA9LziGBlFrAVt6xZHKs3LIOjot4ckttledSiy7Kk5+C7ffEyLlrYz2UNL7oSfdsrE+Sd52cBxR4YQ9qClwoA=
before_install: 
- gem install travis-artifacts
jdk: 
- oraclejdk7
